CREATE TABLE [Account] (
  [ID] VARCHAR(100) PRIMARY KEY,
  [USERNAME] VARCHAR(100) UNIQUE NOT NULL,
  [PASSWORD] VARCHAR(500) NOT NULL,
  [ROLES] varchar(100) NOT NULL,
  [EMAIL] varchar(500) UNIQUE,
  [LAST_LOGIN] DATETIME DEFAULT (now())
)
GO

CREATE TABLE [ROOM] (
  [ID] varchar(100) PRIMARY KEY,
  [TYPE] varchar(100) NOT NULL
)
GO

CREATE TABLE [ROOM_ACCOUNT] (
  [ID] integer PRIMARY KEY,
  [USERNAME] varchar(100) NOT NULL,
  [ROOM_ID] varchar(100) NOT NULL
)
GO

CREATE TABLE [MESSAGE] (
  [ID] VARCHAR(100) PRIMARY KEY,
  [CONTENT] varchar(500) NOT NULL,
  [ROOM_ID] varchar(100) NOT NULL,
  [FILENAME] varchar(100) DEFAULT (null),
  [CREATE_AT] datetime,
  [DELETE_AT] datetime
)
GO

CREATE TABLE [RELATIONSHIP] (
  [ID] varchar(100) PRIMARY KEY,
  [USER1] varchar(100) NOT NULL,
  [USER2] varchar(100) NOT NULL,
  [TYPE] varchar(100) DEFAULT 'NORMAL'
)
GO

CREATE TABLE [NOTIFICATION] (
  [ID] VARCHAR(100) PRIMARY KEY,
  [USERNAME] VARCHAR(100) NOT NULL,
  [TITLE] varchar(200) NOT NULL,
  [DESCRIPTION] nvarchar(500) NOT NULL,
  [TYPE] varchar(100) NOT NULL,
  [SEEN] Bit DEFAULT 0,
  [SOURCE] varchar(100) DEFAULT 'SYSTEM'
)
GO

CREATE TABLE [FILE_URL] (
  [ID] VARCHAR(1000) PRIMARY KEY,
  [FILENAME] VARCHAR(500),
  [ORIGINAL_NAME] varchar(500) NOT NULL,
  [IS_IMAGE] bool DEFAULT (false)
)
GO

ALTER TABLE [ROOM_ACCOUNT] ADD FOREIGN KEY ([ROOM_ID]) REFERENCES [ROOM] ([ID])
GO

ALTER TABLE [ROOM_ACCOUNT] ADD FOREIGN KEY ([USERNAME]) REFERENCES [Account] ([USERNAME])
GO

ALTER TABLE [ROOM] ADD FOREIGN KEY ([ID]) REFERENCES [MESSAGE] ([ROOM_ID])
GO

ALTER TABLE [Account] ADD FOREIGN KEY ([USERNAME]) REFERENCES [RELATIONSHIP] ([USER1])
GO

ALTER TABLE [Account] ADD FOREIGN KEY ([USERNAME]) REFERENCES [RELATIONSHIP] ([USER2])
GO

ALTER TABLE [Account] ADD FOREIGN KEY ([USERNAME]) REFERENCES [NOTIFICATION] ([USERNAME])
GO

ALTER TABLE [FILE_URL] ADD FOREIGN KEY ([FILENAME]) REFERENCES [MESSAGE] ([FILENAME])
GO
