--CREATE DATABASE CHATING;

USE CHATING

CREATE TABLE MESSAGE (
	ID VARCHAR(100),
	USERNAME VARCHAR(100),
	FRIENDUSERNAME VARCHAR(100),
	CONTENT NVARCHAR(500),
	TIME DATETIME
)

INSERT INTO MESSAGE VALUES (
	'harryguci_ngocanh_0001',
	'harryguci',
	'ngocanh',
	N'hello world !!!',
	'2023-02-26 20:59:00'
)