CREATE TABLE [dbo].[Account] (
    [ID]         VARCHAR (100) NOT NULL,
    [USERNAME]   VARCHAR (100) NOT NULL,
    [PASSWORD]   VARCHAR (500) NOT NULL,
    [ROLES]      VARCHAR (100) NOT NULL,
    [EMAIL]      VARCHAR (500) NULL,
    [LAST_LOGIN] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([EMAIL] ASC),
    UNIQUE NONCLUSTERED ([USERNAME] ASC)
);

GO

CREATE TABLE [dbo].[FriendRequest] (
    [Id]        VARCHAR (10)  NOT NULL,
    [USER1]     VARCHAR (100) NOT NULL,
    [USER2]     VARCHAR (100) NOT NULL,
    [ACCEPTED]  BIT           DEFAULT ((0)) NULL,
    [CREATE_AT] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([USER1]) REFERENCES [dbo].[Account] ([USERNAME]),
    FOREIGN KEY ([USER2]) REFERENCES [dbo].[Account] ([USERNAME])
);

GO

CREATE TABLE [dbo].[MESSAGE] (
    [ID]        VARCHAR (100) NOT NULL,
    [USERNAME]  VARCHAR (100) NOT NULL,
    [CONTENT]   VARCHAR (500) NOT NULL,
    [ROOM_ID]   VARCHAR (100) NOT NULL,
    [FILENAME]  VARCHAR (100) DEFAULT (NULL) NULL,
    [CREATE_AT] DATETIME      NULL,
    [DELETE_AT] DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

GO

CREATE TABLE [dbo].[NOTIFICATION] (
    [ID]          VARCHAR (100)  NOT NULL,
    [USERNAME]    VARCHAR (100)  NOT NULL,
    [TITLE]       VARCHAR (200)  NOT NULL,
    [DESCRIPTION] NVARCHAR (500) NOT NULL,
    [TYPE]        VARCHAR (100)  NOT NULL,
    [SEEN]        BIT            DEFAULT ((0)) NULL,
    [SOURCE]      VARCHAR (100)  DEFAULT ('SYSTEM') NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

GO

CREATE TABLE [dbo].[RELATIONSHIP] (
    [ID]    VARCHAR (100) NOT NULL,
    [USER1] VARCHAR (100) NOT NULL,
    [USER2] VARCHAR (100) NOT NULL,
    [TYPE]  VARCHAR (100) DEFAULT ('NORMAL') NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

GO

CREATE TABLE [dbo].[ROOM] (
    [ID]   VARCHAR (100) NOT NULL,
    [TYPE] VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

GO

CREATE TABLE [dbo].[ROOM_ACCOUNT] (
    [ID]       INT           NOT NULL,
    [USERNAME] VARCHAR (100) NOT NULL,
    [ROOM_ID]  VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([ROOM_ID]) REFERENCES [dbo].[ROOM] ([ID]),
    FOREIGN KEY ([ROOM_ID]) REFERENCES [dbo].[ROOM] ([ID]),
    FOREIGN KEY ([USERNAME]) REFERENCES [dbo].[Account] ([USERNAME])
);

