CREATE TABLE ROOM_USER (
	ID	VARCHAR(100) PRIMARY KEY,
	USERNAME VARCHAR(100) NOT NULL,
	ROOM_ID NVARCHAR(10) NOT NULL,
	CONSTRAINT ROOM_USER_USERNAME_FK FOREIGN KEY ([USERNAME]) REFERENCES [dbo].[Account] ([USERNAME]),
	CONSTRAINT ROOM_USER_ROOMID_FK FOREIGN KEY ([ROOM_ID]) REFERENCES [dbo].[ROOMCHAT] ([ID])
)