USE CHATING;

CREATE TABLE ACCOUNT (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	USERNAME VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(1000) NOT NULL,
	ROLES NVARCHAR(50),
	DATEBIRTH DATETIME,
	EMAILL VARCHAR(500) UNIQUE,
	CREATE_AT DATETIME DEFAULT GETDATE(),
	DELETE_AT DATETIME DEFAULT NULL,
)

CREATE TABLE RELATIONSHIP (
	USER1 VARCHAR(100) NOT NULL,
	USER2 VARCHAR(100) NOT NULL,
	LEVEL_FRIEND NVARCHAR(300) NOT NULL,
	CONSTRAINT RELATIONSHIP_USER1_FK FOREIGN KEY (USER1) REFERENCES ACCOUNT(USERNAME),
	CONSTRAINT RELATIONSHIP_USER2_FK FOREIGN KEY (USER2) REFERENCES ACCOUNT(USERNAME),
)